export const UserLabels = {
  Id: "ID",
  Email: "Email",
  Name: "Name",
  InvitationExpiresAt: (date) => `Invitation expires at ${date}`,
  InvitationExpired: "Invitation has expired",
  Reinvite: "Re-invite",
  RevokeInvitation: "Revoke Invitation",
  RevokeConfirmation: (email) => `Revoke the invitation of ${email}? The user will be removed from the list.`,
  Reinvited: (email) => `The invitation has been sent to ${email}`,
  Revoked: (email) => `${email} has been removed`,
  Permissions: "Permissions",
  FirstName: "First Name",
  MiddleName: "Middle Name",
  LastName: "Last Name",
  CreateHeader: 'Invite New User',
  EditHeader: 'Edit User',
  CheckAll: 'Check All',
  UnCheckAll: 'Uncheck All',
  Save: 'Save',
  Invite: 'Invite',
  Cancel: 'Cancel',
  Invoices: 'Invoices',
  SalesOrders: 'Sales Orders',
  Deposits: 'Deposits',
  ProcessPayments: 'Process Payments',
  MaxNumberOfUsers: (count, companyName) => `Max number of users ${count} exceeded. Please contact ${companyName} to increase the limit.`,
} as const;
