export enum SystemAuditActionEnum {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED_WRONG_PASSWORD = 'LOGIN_FAILED_WRONG_PASSWORD',
  LOGIN_FAILED_ACCOUNT_DISABLED = 'LOGIN_FAILED_ACCOUNT_DISABLED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  SELECT_ROLE = 'SELECT_ROLE',
  COMPANY_CREATED = 'COMPANY_CREATED',
  COMPANY_UPDATED = 'COMPANY_UPDATED',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DISABLE_USER = 'DISABLE_USER',
  ENABLE_USER = 'ENABLE_USER',
  DISABLE_COMPANY = 'DISABLE_COMPANY',
  ENABLE_COMPANY = 'ENABLE_COMPANY',
  API_TOKEN_CREATE = 'API_TOKEN_CREATE',
  API_TOKEN_REGENERATE = 'API_TOKEN_REGENERATE',
  API_TOKEN_REVOKE = 'API_TOKEN_REVOKE',
  CREATE_PLATFORM = 'CREATE_PLATFORM',
  UPDATE_PLATFORM = 'UPDATE_PLATFORM',
  PLATFORM_TOKEN_GENERATED = 'PLATFORM_TOKEN_GENERATED',
  DELETE_PLATFORM = 'DELETE_PLATFORM',
  CREATE_SENDGRID_SETTINGS = 'CREATE_SENDGRID_SETTINGS',
  UPDATE_SENDGRID_SETTINGS = 'UPDATE_SENDGRID_SETTINGS',
  DISABLE_SENDGRID_SETTINGS = 'DISABLE_SENDGRID_SETTINGS',
  ENABLE_SENDGRID_SETTINGS = 'ENABLE_SENDGRID_SETTINGS',
  CREATE_PAYMENT_FORM = 'CREATE_PAYMENT_FORM',
  UPDATE_PAYMENT_FORM = 'UPDATE_PAYMENT_FORM',
  DISABLE_PAYMENT_FORM = 'DISABLE_PAYMENT_FORM',
  ENABLE_PAYMENT_FORM = 'ENABLE_PAYMENT_FORM'
}

export const SystemAuditActionName = new Map<string, string>([
  [SystemAuditActionEnum.LOGIN_SUCCESS, 'Logged in'],
  [SystemAuditActionEnum.LOGIN_FAILED_WRONG_PASSWORD, 'Login failed. Wrong password'],
  [SystemAuditActionEnum.LOGIN_FAILED_ACCOUNT_DISABLED, 'Login failed. Disabled account'],
  [SystemAuditActionEnum.PASSWORD_RESET, 'New Password generated'],
  [SystemAuditActionEnum.PASSWORD_RESET_FAILED, 'Password reset failed'],
  [SystemAuditActionEnum.PASSWORD_CHANGED, 'Password changed'],
  [SystemAuditActionEnum.SELECT_ROLE, 'Role selected'],
  [SystemAuditActionEnum.COMPANY_CREATED, 'Company created'],
  [SystemAuditActionEnum.COMPANY_UPDATED, 'Company updated'],
  [SystemAuditActionEnum.CREATE_ROLE, 'Role created'],
  [SystemAuditActionEnum.UPDATE_ROLE, 'Role updated'],
  [SystemAuditActionEnum.DELETE_ROLE, 'Role deleted'],
  [SystemAuditActionEnum.CREATE_USER, 'User created'],
  [SystemAuditActionEnum.UPDATE_USER, 'User updated'],
  [SystemAuditActionEnum.DISABLE_USER, 'User disabled'],
  [SystemAuditActionEnum.ENABLE_USER, 'User enabled'],
  [SystemAuditActionEnum.DISABLE_COMPANY, 'Company disabled'],
  [SystemAuditActionEnum.ENABLE_COMPANY, 'Company enabled'],
  [SystemAuditActionEnum.API_TOKEN_CREATE, 'Company Token generated'],
  [SystemAuditActionEnum.API_TOKEN_REGENERATE, 'Company Token regenerated'],
  [SystemAuditActionEnum.API_TOKEN_REVOKE, 'Company Token revoked'],
  [SystemAuditActionEnum.CREATE_PLATFORM, 'Platform created'],
  [SystemAuditActionEnum.UPDATE_PLATFORM, 'Platform updated'],
  [SystemAuditActionEnum.PLATFORM_TOKEN_GENERATED, 'Platform Token generated'],
  [SystemAuditActionEnum.DELETE_PLATFORM, 'Platform deleted'],
  [SystemAuditActionEnum.CREATE_SENDGRID_SETTINGS, 'Sendgrid Settings created'],
  [SystemAuditActionEnum.UPDATE_SENDGRID_SETTINGS, 'Sendgrid Settings updated'],
  [SystemAuditActionEnum.DISABLE_SENDGRID_SETTINGS, 'Sendgrid Settings disabled'],
  [SystemAuditActionEnum.ENABLE_SENDGRID_SETTINGS, 'Sendgrid Settings enabled'],
  [SystemAuditActionEnum.CREATE_PAYMENT_FORM, 'Payment Form created'],
  [SystemAuditActionEnum.UPDATE_PAYMENT_FORM, 'Payment Form updated'],
  [SystemAuditActionEnum.DISABLE_PAYMENT_FORM, 'Payment Form disabled'],
  [SystemAuditActionEnum.ENABLE_PAYMENT_FORM, 'Payment Form enabled']
]);

export enum CompanyAuditActionEnum {
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  SELECT_ROLE = 'SELECT_ROLE',
  CREATE_ENTITY = 'CREATE_ENTITY',
  UPDATE_ENTITY = 'UPDATE_ENTITY',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DISABLE_USER = 'DISABLE_USER',
  ENABLE_USER = 'ENABLE_USER',
  DISABLE_COMPANY = 'DISABLE_COMPANY',
  ENABLE_COMPANY = 'ENABLE_COMPANY',
  API_TOKEN_CREATE = 'API_TOKEN_CREATE',
  API_TOKEN_REGENERATE = 'API_TOKEN_REGENERATE',
  API_TOKEN_REVOKE = 'API_TOKEN_REVOKE',
  CREATE_PAYMENT_FORM = 'CREATE_PAYMENT_FORM',
  UPDATE_PAYMENT_FORM = 'UPDATE_PAYMENT_FORM',
  DISABLE_PAYMENT_FORM = 'DISABLE_PAYMENT_FORM',
  ENABLE_PAYMENT_FORM = 'ENABLE_PAYMENT_FORM'
}

export const CompanyAuditActionName = new Map<string, string>([
  [CompanyAuditActionEnum.PASSWORD_RESET, 'New Password generated'],
  [CompanyAuditActionEnum.PASSWORD_CHANGED, 'Password changed'],
  [CompanyAuditActionEnum.SELECT_ROLE, 'Role selected'],
  [CompanyAuditActionEnum.CREATE_ENTITY, 'Entity created'],
  [CompanyAuditActionEnum.UPDATE_ENTITY, 'Entity updated'],
  [CompanyAuditActionEnum.CREATE_ROLE, 'Role created'],
  [CompanyAuditActionEnum.UPDATE_ROLE, 'Role updated'],
  [CompanyAuditActionEnum.DELETE_ROLE, 'Role deleted'],
  [CompanyAuditActionEnum.CREATE_USER, 'User created'],
  [CompanyAuditActionEnum.UPDATE_USER, 'User updated'],
  [CompanyAuditActionEnum.DISABLE_USER, 'User disabled'],
  [CompanyAuditActionEnum.ENABLE_USER, 'User enabled'],
  [CompanyAuditActionEnum.DISABLE_COMPANY, 'Company disabled'],
  [CompanyAuditActionEnum.ENABLE_COMPANY, 'Company enabled'],
  [CompanyAuditActionEnum.API_TOKEN_CREATE, 'API Token created'],
  [CompanyAuditActionEnum.API_TOKEN_REGENERATE, 'API Token regenerated'],
  [CompanyAuditActionEnum.API_TOKEN_REVOKE, 'API Token revoked'],
  [CompanyAuditActionEnum.CREATE_PAYMENT_FORM, 'Payment Form created'],
  [CompanyAuditActionEnum.UPDATE_PAYMENT_FORM, 'Payment Form updated'],
  [CompanyAuditActionEnum.DISABLE_PAYMENT_FORM, 'Payment Form disabled'],
  [CompanyAuditActionEnum.ENABLE_PAYMENT_FORM, 'Payment Form enabled']
]);

export const AuditActionEnum = SystemAuditActionEnum;
