export const CompanySettingsLabels = {
  AllowPartialPaymentsOf: "Allow Partial Payments Of ",
  AllowInvoicePartialPayments: "Invoices",
  AllowSalesOrderPartialPayments: "Sales Orders",
  AllowDepositPartialPayments: "Deposits",
  PaymentMethods: "Payment Methods",
  NoPaymentMethods: "There are no available Payment Methods",
  AuthorizationMessage: "Authorization Message",
  CCAuthorizationMessage: "CC Authorization Message",
  CCSurchargesAuthorizationMessage: "CC Surcharges Authorization Message",
  ACHAuthorizationMessage: "ACH Authorization Message",
  CCPaymentAmountMaxValue: "Credit Card Transaction Limit",
  NoLimit: "No Limit",
  EmailSale: 'Email Sales (Invoices, Sales Orders, Deposit)',
  EmailSaleHeaderEnabled: 'Email Sale Header Enabled',
  EmailReceipt: 'Email Customer Receipt Upon Approval',
  NotificationOfCustomerPayment: 'Notification of Customer Payment',
  PaymentFormSubmissionNotification: 'Payment Form Submission Notification',
  NotificationEmail: 'Email To',
  NotificationEmailPlaceholder: 'Separate Multiple Emails with Commas',
  SalesEmailOptionHint: "Platform-level settings",
  AllowCustomersManageTheirPaymentMethodsCreatedByMerchant: 'Allow Customers To Manage Their Payment Methods Created By Merchant',
  SaleEvents: "Sale Events",
  PaymentMethodEvents: "Payment Method Events",
  CustomerEvents: "Customer Events",
  EnableSurcharges: "Enable Surcharges",
  SurchargePercent: "Surcharge Percent",
  SurchargeHint: (min, max) => `The Surcharge Percent must be from ${min}% to ${max}%`,
  MailingMethod: "Mailing Method",
  FromAddress: "From Address",
  SMTPServer: "SMTP Server",
  SecurityMode: "Security Mode",
  Port: "Port",
  User: "User",
  Password: "Password",
} as const;
