export const CustomerPreFilledSignInModalLabels = {
  Email: 'Email',
  OldPassword: 'Old Password',
  Password: 'Password',
  NewPassword: 'New Password',
  ConfirmPassword: 'Confirm Password',
  Register: 'Register',
  RegisterHeader: (name: string) => `Register ${name}`,
  ConfirmRegistrationHeader: 'Registration',
  ConfirmRegistration: (minutes: number) => `Thank you for registering!\n\nPlease check you email and complete the verification steps within ${minutes} minutes.\nEmail verification is required to log in.`,
  ForgotPassword: 'Forgot Password',
  ForgotPasswordHeader: (name: string) => `Forgot ${name} Password?`,
  SignIn: 'Sign In',
  SignInHeader: (name: string) => `Hello, ${name}`,
  ResetPassword: 'Reset Password',
  ChangePassword: 'Change Password',
  Continue: 'Continue',
  ChangePasswordHeader: (name: string) => `Changing ${name} Password`,
  BackToSignIn: 'Back to Sign In',
  SignInMessage: 'Already have an account?',
  RegisterMessage: 'Don\'t have an account?',
  ConfirmRegistrationMessage: 'To complete your registration follow the link in your confirmation email.',
  ResetPasswordConfirmMessage: 'To reset password follow instructions in your email.',
  PasswordChangedMessage: 'Password changed',
  PasswordHint: (minLength, maxLength) => `The password must be ${minLength}-${maxLength} characters long, contain upper and lower case and special characters`,
} as const;
