export enum InvoiceItemDetailTypeEnum {
  SALES_ITEM_LINE_DETAIL = 'SALES_ITEM_LINE_DETAIL',
  DESCRIPTION_ONLY = 'DESCRIPTION_ONLY',
  GROUP_LINE_DETAIL = 'GROUP_LINE_DETAIL',
  SUBTOTAL_LINE = 'SUBTOTAL_LINE'
}
