export enum SaleEmailAuthorizationMessagePlaceholderScopeEnum {
  CC_AUTHORIZATION_MESSAGE = 'CC_AUTHORIZATION_MESSAGE',
  CC_SURCHARGES_AUTHORIZATION_MESSAGE = 'CC_SURCHARGES_AUTHORIZATION_MESSAGE',
  ACH_AUTHORIZATION_MESSAGE = 'ACH_AUTHORIZATION_MESSAGE'
}
