export enum CountryISOEnum {
  US = 'US',
  CA = 'CA',
  AF = 'AF',
  AX = 'AX',
  AL = 'AL',
  DZ = 'DZ',
  AS = 'AS',
  AD = 'AD',
  AO = 'AO',
  AI = 'AI',
  AQ = 'AQ',
  AG = 'AG',
  AR = 'AR',
  AM = 'AM',
  AW = 'AW',
  AU = 'AU',
  AT = 'AT',
  AZ = 'AZ',
  BS = 'BS',
  BH = 'BH',
  BD = 'BD',
  BB = 'BB',
  BY = 'BY',
  BE = 'BE',
  BZ = 'BZ',
  BJ = 'BJ',
  BM = 'BM',
  BT = 'BT',
  BO = 'BO',
  BQ = 'BQ',
  BA = 'BA',
  BW = 'BW',
  BV = 'BV',
  BR = 'BR',
  IO = 'IO',
  BN = 'BN',
  BG = 'BG',
  BF = 'BF',
  BI = 'BI',
  CV = 'CV',
  KH = 'KH',
  CM = 'CM',
  KY = 'KY',
  CF = 'CF',
  TD = 'TD',
  CL = 'CL',
  CN = 'CN',
  CX = 'CX',
  CC = 'CC',
  CO = 'CO',
  KM = 'KM',
  CG = 'CG',
  CD = 'CD',
  CK = 'CK',
  CR = 'CR',
  CI = 'CI',
  HR = 'HR',
  CU = 'CU',
  CW = 'CW',
  CY = 'CY',
  CZ = 'CZ',
  DK = 'DK',
  DJ = 'DJ',
  DM = 'DM',
  DO = 'DO',
  EC = 'EC',
  EG = 'EG',
  SV = 'SV',
  GQ = 'GQ',
  ER = 'ER',
  EE = 'EE',
  SZ = 'SZ',
  ET = 'ET',
  FK = 'FK',
  FO = 'FO',
  FJ = 'FJ',
  FI = 'FI',
  FR = 'FR',
  GF = 'GF',
  PF = 'PF',
  TF = 'TF',
  GA = 'GA',
  GM = 'GM',
  GE = 'GE',
  DE = 'DE',
  GH = 'GH',
  GI = 'GI',
  GR = 'GR',
  GL = 'GL',
  GD = 'GD',
  GP = 'GP',
  GU = 'GU',
  GT = 'GT',
  GG = 'GG',
  GN = 'GN',
  GW = 'GW',
  GY = 'GY',
  HT = 'HT',
  HM = 'HM',
  VA = 'VA',
  HN = 'HN',
  HK = 'HK',
  HU = 'HU',
  IS = 'IS',
  IN = 'IN',
  ID = 'ID',
  IR = 'IR',
  IQ = 'IQ',
  IE = 'IE',
  IM = 'IM',
  IL = 'IL',
  IT = 'IT',
  JM = 'JM',
  JP = 'JP',
  JE = 'JE',
  JO = 'JO',
  KZ = 'KZ',
  KE = 'KE',
  KI = 'KI',
  KR = 'KR',
  KW = 'KW',
  KG = 'KG',
  LA = 'LA',
  LV = 'LV',
  LB = 'LB',
  LS = 'LS',
  LR = 'LR',
  LY = 'LY',
  LI = 'LI',
  LT = 'LT',
  LU = 'LU',
  MO = 'MO',
  MG = 'MG',
  MW = 'MW',
  MY = 'MY',
  MV = 'MV',
  ML = 'ML',
  MT = 'MT',
  MH = 'MH',
  MQ = 'MQ',
  MR = 'MR',
  MU = 'MU',
  YT = 'YT',
  MX = 'MX',
  FM = 'FM',
  MD = 'MD',
  MC = 'MC',
  MN = 'MN',
  ME = 'ME',
  MS = 'MS',
  MA = 'MA',
  MZ = 'MZ',
  MM = 'MM',
  NA = 'NA',
  NR = 'NR',
  NP = 'NP',
  NL = 'NL',
  NC = 'NC',
  NZ = 'NZ',
  NI = 'NI',
  NE = 'NE',
  NG = 'NG',
  NU = 'NU',
  NF = 'NF',
  MK = 'MK',
  MP = 'MP',
  NO = 'NO',
  OM = 'OM',
  PK = 'PK',
  PW = 'PW',
  PS = 'PS',
  PA = 'PA',
  PG = 'PG',
  PY = 'PY',
  PE = 'PE',
  PH = 'PH',
  PN = 'PN',
  PL = 'PL',
  PT = 'PT',
  PR = 'PR',
  QA = 'QA',
  RE = 'RE',
  RO = 'RO',
  RU = 'RU',
  RW = 'RW',
  BL = 'BL',
  SH = 'SH',
  KN = 'KN',
  LC = 'LC',
  MF = 'MF',
  PM = 'PM',
  VC = 'VC',
  WS = 'WS',
  SM = 'SM',
  ST = 'ST',
  SA = 'SA',
  SN = 'SN',
  RS = 'RS',
  SC = 'SC',
  SL = 'SL',
  SG = 'SG',
  SX = 'SX',
  SK = 'SK',
  SI = 'SI',
  SB = 'SB',
  SO = 'SO',
  ZA = 'ZA',
  GS = 'GS',
  SS = 'SS',
  ES = 'ES',
  LK = 'LK',
  SD = 'SD',
  SR = 'SR',
  SJ = 'SJ',
  SE = 'SE',
  CH = 'CH',
  SY = 'SY',
  TW = 'TW',
  TJ = 'TJ',
  TZ = 'TZ',
  TH = 'TH',
  TL = 'TL',
  TG = 'TG',
  TK = 'TK',
  TO = 'TO',
  TT = 'TT',
  TN = 'TN',
  TR = 'TR',
  TM = 'TM',
  TC = 'TC',
  TV = 'TV',
  UG = 'UG',
  UA = 'UA',
  AE = 'AE',
  GB = 'GB',
  UM = 'UM',
  UY = 'UY',
  UZ = 'UZ',
  VU = 'VU',
  VE = 'VE',
  VN = 'VN',
  VG = 'VG',
  VI = 'VI',
  WF = 'WF',
  EH = 'EH',
  YE = 'YE',
  ZM = 'ZM',
  ZW = 'ZW'
}

export const CountryISOLong = Object.keys(CountryISOEnum);
export const CountryISOShort = [CountryISOEnum.US, CountryISOEnum.CA];

export class CountryISO {
  code: CountryISOEnum;
  code3: string;
  name: string;

  static findByCode(code: string): CountryISO {
    return CountryISOValues.find(country => country.code == code);
  }
}

export const CountryISOValues: CountryISO[] = [
  {code: CountryISOEnum.US, code3: "USA", name: "United States of America"},
  {code: CountryISOEnum.CA, code3: "CAN", name: "Canada"},
  {code: CountryISOEnum.AF, code3: "AFG", name: "Afghanistan"},
  {code: CountryISOEnum.AX, code3: "ALA", name: "Åland Islands"},
  {code: CountryISOEnum.AL, code3: "ALB", name: "Albania"},
  {code: CountryISOEnum.DZ, code3: "DZA", name: "Algeria"},
  {code: CountryISOEnum.AS, code3: "ASM", name: "American Samoa"},
  {code: CountryISOEnum.AD, code3: "AND", name: "Andorra"},
  {code: CountryISOEnum.AO, code3: "AGO", name: "Angola"},
  {code: CountryISOEnum.AI, code3: "AIA", name: "Anguilla"},
  {code: CountryISOEnum.AQ, code3: "ATA", name: "Antarctica"},
  {code: CountryISOEnum.AG, code3: "ATG", name: "Antigua and Barbuda"},
  {code: CountryISOEnum.AR, code3: "ARG", name: "Argentina"},
  {code: CountryISOEnum.AM, code3: "ARM", name: "Armenia"},
  {code: CountryISOEnum.AW, code3: "ABW", name: "Aruba"},
  {code: CountryISOEnum.AU, code3: "AUS", name: "Australia"},
  {code: CountryISOEnum.AT, code3: "AUT", name: "Austria"},
  {code: CountryISOEnum.AZ, code3: "AZE", name: "Azerbaijan"},
  {code: CountryISOEnum.BS, code3: "BHS", name: "Bahamas"},
  {code: CountryISOEnum.BH, code3: "BHR", name: "Bahrain"},
  {code: CountryISOEnum.BD, code3: "BGD", name: "Bangladesh"},
  {code: CountryISOEnum.BB, code3: "BRB", name: "Barbados"},
  {code: CountryISOEnum.BY, code3: "BLR", name: "Belarus"},
  {code: CountryISOEnum.BE, code3: "BEL", name: "Belgium"},
  {code: CountryISOEnum.BZ, code3: "BLZ", name: "Belize"},
  {code: CountryISOEnum.BJ, code3: "BEN", name: "Benin"},
  {code: CountryISOEnum.BM, code3: "BMU", name: "Bermuda"},
  {code: CountryISOEnum.BT, code3: "BTN", name: "Bhutan"},
  {code: CountryISOEnum.BO, code3: "BOL", name: "Bolivia (Plurinational State of)"},
  {code: CountryISOEnum.BQ, code3: "BES", name: "Bonaire, Sint Eustatius and Saba"},
  {code: CountryISOEnum.BA, code3: "BIH", name: "Bosnia and Herzegovina"},
  {code: CountryISOEnum.BW, code3: "BWA", name: "Botswana"},
  {code: CountryISOEnum.BV, code3: "BVT", name: "Bouvet Island"},
  {code: CountryISOEnum.BR, code3: "BRA", name: "Brazil"},
  {code: CountryISOEnum.IO, code3: "IOT", name: "British Indian Ocean Territory"},
  {code: CountryISOEnum.BN, code3: "BRN", name: "Brunei Darussalam"},
  {code: CountryISOEnum.BG, code3: "BGR", name: "Bulgaria"},
  {code: CountryISOEnum.BF, code3: "BFA", name: "Burkina Faso"},
  {code: CountryISOEnum.BI, code3: "BDI", name: "Burundi"},
  {code: CountryISOEnum.CV, code3: "CPV", name: "Cabo Verde"},
  {code: CountryISOEnum.KH, code3: "KHM", name: "Cambodia"},
  {code: CountryISOEnum.CM, code3: "CMR", name: "Cameroon"},
  {code: CountryISOEnum.KY, code3: "CYM", name: "Cayman Islands"},
  {code: CountryISOEnum.CF, code3: "CAF", name: "Central African Republic"},
  {code: CountryISOEnum.TD, code3: "TCD", name: "Chad"},
  {code: CountryISOEnum.CL, code3: "CHL", name: "Chile"},
  {code: CountryISOEnum.CN, code3: "CHN", name: "China"},
  {code: CountryISOEnum.CX, code3: "CXR", name: "Christmas Island"},
  {code: CountryISOEnum.CC, code3: "CCK", name: "Cocos (Keeling) Islands"},
  {code: CountryISOEnum.CO, code3: "COL", name: "Colombia"},
  {code: CountryISOEnum.KM, code3: "COM", name: "Comoros"},
  {code: CountryISOEnum.CG, code3: "COG", name: "Congo"},
  {code: CountryISOEnum.CD, code3: "COD", name: "Congo (Democratic Republic of the)"},
  {code: CountryISOEnum.CK, code3: "COK", name: "Cook Islands"},
  {code: CountryISOEnum.CR, code3: "CRI", name: "Costa Rica"},
  {code: CountryISOEnum.CI, code3: "CIV", name: "Côte d'Ivoire"},
  {code: CountryISOEnum.HR, code3: "HRV", name: "Croatia"},
  {code: CountryISOEnum.CU, code3: "CUB", name: "Cuba"},
  {code: CountryISOEnum.CW, code3: "CUW", name: "Curaçao"},
  {code: CountryISOEnum.CY, code3: "CYP", name: "Cyprus"},
  {code: CountryISOEnum.CZ, code3: "CZE", name: "Czech Republic"},
  {code: CountryISOEnum.DK, code3: "DNK", name: "Denmark"},
  {code: CountryISOEnum.DJ, code3: "DJI", name: "Djibouti"},
  {code: CountryISOEnum.DM, code3: "DMA", name: "Dominica"},
  {code: CountryISOEnum.DO, code3: "DOM", name: "Dominican Republic"},
  {code: CountryISOEnum.EC, code3: "ECU", name: "Ecuador"},
  {code: CountryISOEnum.EG, code3: "EGY", name: "Egypt"},
  {code: CountryISOEnum.SV, code3: "SLV", name: "El Salvador"},
  {code: CountryISOEnum.GQ, code3: "GNQ", name: "Equatorial Guinea"},
  {code: CountryISOEnum.ER, code3: "ERI", name: "Eritrea"},
  {code: CountryISOEnum.EE, code3: "EST", name: "Estonia"},
  {code: CountryISOEnum.ET, code3: "ETH", name: "Ethiopia"},
  {code: CountryISOEnum.FK, code3: "FLK", name: "Falkland Islands (Malvinas)"},
  {code: CountryISOEnum.FO, code3: "FRO", name: "Faroe Islands"},
  {code: CountryISOEnum.FJ, code3: "FJI", name: "Fiji"},
  {code: CountryISOEnum.FI, code3: "FIN", name: "Finland"},
  {code: CountryISOEnum.FR, code3: "FRA", name: "France"},
  {code: CountryISOEnum.GF, code3: "GUF", name: "French Guiana"},
  {code: CountryISOEnum.PF, code3: "PYF", name: "French Polynesia"},
  {code: CountryISOEnum.TF, code3: "ATF", name: "French Southern Territories"},
  {code: CountryISOEnum.GA, code3: "GAB", name: "Gabon"},
  {code: CountryISOEnum.GM, code3: "GMB", name: "Gambia"},
  {code: CountryISOEnum.GE, code3: "GEO", name: "Georgia"},
  {code: CountryISOEnum.DE, code3: "DEU", name: "Germany"},
  {code: CountryISOEnum.GH, code3: "GHA", name: "Ghana"},
  {code: CountryISOEnum.GI, code3: "GIB", name: "Gibraltar"},
  {code: CountryISOEnum.GR, code3: "GRC", name: "Greece"},
  {code: CountryISOEnum.GL, code3: "GRL", name: "Greenland"},
  {code: CountryISOEnum.GD, code3: "GRD", name: "Grenada"},
  {code: CountryISOEnum.GP, code3: "GLP", name: "Guadeloupe"},
  {code: CountryISOEnum.GU, code3: "GUM", name: "Guam"},
  {code: CountryISOEnum.GT, code3: "GTM", name: "Guatemala"},
  {code: CountryISOEnum.GG, code3: "GGY", name: "Guernsey"},
  {code: CountryISOEnum.GN, code3: "GIN", name: "Guinea"},
  {code: CountryISOEnum.GW, code3: "GNB", name: "Guinea-Bissau"},
  {code: CountryISOEnum.GY, code3: "GUY", name: "Guyana"},
  {code: CountryISOEnum.HT, code3: "HTI", name: "Haiti"},
  {code: CountryISOEnum.HM, code3: "HMD", name: "Heard Island and McDonald Islands"},
  {code: CountryISOEnum.VA, code3: "VAT", name: "Holy See"},
  {code: CountryISOEnum.HN, code3: "HND", name: "Honduras"},
  {code: CountryISOEnum.HK, code3: "HKG", name: "Hong Kong"},
  {code: CountryISOEnum.HU, code3: "HUN", name: "Hungary"},
  {code: CountryISOEnum.IS, code3: "ISL", name: "Iceland"},
  {code: CountryISOEnum.IN, code3: "IND", name: "India"},
  {code: CountryISOEnum.ID, code3: "IDN", name: "Indonesia"},
  {code: CountryISOEnum.IR, code3: "IRN", name: "Iran (Islamic Republic of)"},
  {code: CountryISOEnum.IQ, code3: "IRQ", name: "Iraq"},
  {code: CountryISOEnum.IE, code3: "IRL", name: "Ireland"},
  {code: CountryISOEnum.IM, code3: "IMN", name: "Isle of Man"},
  {code: CountryISOEnum.IL, code3: "ISR", name: "Israel"},
  {code: CountryISOEnum.IT, code3: "ITA", name: "Italy"},
  {code: CountryISOEnum.JM, code3: "JAM", name: "Jamaica"},
  {code: CountryISOEnum.JP, code3: "JPN", name: "Japan"},
  {code: CountryISOEnum.JE, code3: "JEY", name: "Jersey"},
  {code: CountryISOEnum.JO, code3: "JOR", name: "Jordan"},
  {code: CountryISOEnum.KZ, code3: "KAZ", name: "Kazakhstan"},
  {code: CountryISOEnum.KE, code3: "KEN", name: "Kenya"},
  {code: CountryISOEnum.KI, code3: "KIR", name: "Kiribati"},
  {code: CountryISOEnum.KR, code3: "KOR", name: "Korea (Republic of)"},
  {code: CountryISOEnum.KW, code3: "KWT", name: "Kuwait"},
  {code: CountryISOEnum.KG, code3: "KGZ", name: "Kyrgyzstan"},
  {code: CountryISOEnum.LA, code3: "LAO", name: "Lao People's Democratic Republic"},
  {code: CountryISOEnum.LV, code3: "LVA", name: "Latvia"},
  {code: CountryISOEnum.LB, code3: "LBN", name: "Lebanon"},
  {code: CountryISOEnum.LS, code3: "LSO", name: "Lesotho"},
  {code: CountryISOEnum.LR, code3: "LBR", name: "Liberia"},
  {code: CountryISOEnum.LY, code3: "LBY", name: "Libya"},
  {code: CountryISOEnum.LI, code3: "LIE", name: "Liechtenstein"},
  {code: CountryISOEnum.LT, code3: "LTU", name: "Lithuania"},
  {code: CountryISOEnum.LU, code3: "LUX", name: "Luxembourg"},
  {code: CountryISOEnum.MO, code3: "MAC", name: "Macao"},
  {code: CountryISOEnum.MG, code3: "MDG", name: "Madagascar"},
  {code: CountryISOEnum.MW, code3: "MWI", name: "Malawi"},
  {code: CountryISOEnum.MY, code3: "MYS", name: "Malaysia"},
  {code: CountryISOEnum.MV, code3: "MDV", name: "Maldives"},
  {code: CountryISOEnum.ML, code3: "MLI", name: "Mali"},
  {code: CountryISOEnum.MT, code3: "MLT", name: "Malta"},
  {code: CountryISOEnum.MH, code3: "MHL", name: "Marshall Islands"},
  {code: CountryISOEnum.MQ, code3: "MTQ", name: "Martinique"},
  {code: CountryISOEnum.MR, code3: "MRT", name: "Mauritania"},
  {code: CountryISOEnum.MU, code3: "MUS", name: "Mauritius"},
  {code: CountryISOEnum.YT, code3: "MYT", name: "Mayotte"},
  {code: CountryISOEnum.MX, code3: "MEX", name: "Mexico"},
  {code: CountryISOEnum.FM, code3: "FSM", name: "Micronesia (Federated States of)"},
  {code: CountryISOEnum.MD, code3: "MDA", name: "Moldova (Republic of)"},
  {code: CountryISOEnum.MC, code3: "MCO", name: "Monaco"},
  {code: CountryISOEnum.MN, code3: "MNG", name: "Mongolia"},
  {code: CountryISOEnum.ME, code3: "MNE", name: "Montenegro"},
  {code: CountryISOEnum.MS, code3: "MSR", name: "Montserrat"},
  {code: CountryISOEnum.MA, code3: "MAR", name: "Morocco"},
  {code: CountryISOEnum.MZ, code3: "MOZ", name: "Mozambique"},
  {code: CountryISOEnum.MM, code3: "MMR", name: "Myanmar"},
  {code: CountryISOEnum.NA, code3: "NAM", name: "Namibia"},
  {code: CountryISOEnum.NR, code3: "NRU", name: "Nauru"},
  {code: CountryISOEnum.NP, code3: "NPL", name: "Nepal"},
  {code: CountryISOEnum.NL, code3: "NLD", name: "Netherlands"},
  {code: CountryISOEnum.NC, code3: "NCL", name: "New Caledonia"},
  {code: CountryISOEnum.NZ, code3: "NZL", name: "New Zealand"},
  {code: CountryISOEnum.NI, code3: "NIC", name: "Nicaragua"},
  {code: CountryISOEnum.NE, code3: "NER", name: "Niger"},
  {code: CountryISOEnum.NG, code3: "NGA", name: "Nigeria"},
  {code: CountryISOEnum.NU, code3: "NIU", name: "Niue"},
  {code: CountryISOEnum.NF, code3: "NFK", name: "Norfolk Island"},
  {code: CountryISOEnum.MK, code3: "MKD", name: "North Macedonia"},
  {code: CountryISOEnum.MP, code3: "MNP", name: "Northern Mariana Islands"},
  {code: CountryISOEnum.NO, code3: "NOR", name: "Norway"},
  {code: CountryISOEnum.OM, code3: "OMN", name: "Oman"},
  {code: CountryISOEnum.PK, code3: "PAK", name: "Pakistan"},
  {code: CountryISOEnum.PW, code3: "PLW", name: "Palau"},
  {code: CountryISOEnum.PS, code3: "PSE", name: "Palestine, State of"},
  {code: CountryISOEnum.PA, code3: "PAN", name: "Panama"},
  {code: CountryISOEnum.PG, code3: "PNG", name: "Papua New Guinea"},
  {code: CountryISOEnum.PY, code3: "PRY", name: "Paraguay"},
  {code: CountryISOEnum.PE, code3: "PER", name: "Peru"},
  {code: CountryISOEnum.PH, code3: "PHL", name: "Philippines"},
  {code: CountryISOEnum.PN, code3: "PCN", name: "Pitcairn"},
  {code: CountryISOEnum.PL, code3: "POL", name: "Poland"},
  {code: CountryISOEnum.PT, code3: "PRT", name: "Portugal"},
  {code: CountryISOEnum.PR, code3: "PRI", name: "Puerto Rico"},
  {code: CountryISOEnum.QA, code3: "QAT", name: "Qatar"},
  {code: CountryISOEnum.RE, code3: "REU", name: "Réunion"},
  {code: CountryISOEnum.RO, code3: "ROU", name: "Romania"},
  {code: CountryISOEnum.RU, code3: "RUS", name: "Russian Federation"},
  {code: CountryISOEnum.RW, code3: "RWA", name: "Rwanda"},
  {code: CountryISOEnum.BL, code3: "BLM", name: "Saint Barthélemy"},
  {code: CountryISOEnum.SH, code3: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha"},
  {code: CountryISOEnum.KN, code3: "KNA", name: "Saint Kitts and Nevis"},
  {code: CountryISOEnum.LC, code3: "LCA", name: "Saint Lucia"},
  {code: CountryISOEnum.MF, code3: "MAF", name: "Saint Martin (French part)"},
  {code: CountryISOEnum.PM, code3: "SPM", name: "Saint Pierre and Miquelon"},
  {code: CountryISOEnum.VC, code3: "VCT", name: "Saint Vincent and the Grenadines"},
  {code: CountryISOEnum.WS, code3: "WSM", name: "Samoa"},
  {code: CountryISOEnum.SM, code3: "SMR", name: "San Marino"},
  {code: CountryISOEnum.ST, code3: "STP", name: "Sao Tome and Principe"},
  {code: CountryISOEnum.SA, code3: "SAU", name: "Saudi Arabia"},
  {code: CountryISOEnum.SN, code3: "SEN", name: "Senegal"},
  {code: CountryISOEnum.RS, code3: "SRB", name: "Serbia"},
  {code: CountryISOEnum.SC, code3: "SYC", name: "Seychelles"},
  {code: CountryISOEnum.SL, code3: "SLE", name: "Sierra Leone"},
  {code: CountryISOEnum.SG, code3: "SGP", name: "Singapore"},
  {code: CountryISOEnum.SX, code3: "SXM", name: "Sint Maarten (Dutch part)"},
  {code: CountryISOEnum.SK, code3: "SVK", name: "Slovakia"},
  {code: CountryISOEnum.SI, code3: "SVN", name: "Slovenia"},
  {code: CountryISOEnum.SB, code3: "SLB", name: "Solomon Islands"},
  {code: CountryISOEnum.SO, code3: "SOM", name: "Somalia"},
  {code: CountryISOEnum.ZA, code3: "ZAF", name: "South Africa"},
  {code: CountryISOEnum.GS, code3: "SGS", name: "South Georgia and the South Sandwich Islands"},
  {code: CountryISOEnum.SS, code3: "SSD", name: "South Sudan"},
  {code: CountryISOEnum.ES, code3: "ESP", name: "Spain"},
  {code: CountryISOEnum.LK, code3: "LKA", name: "Sri Lanka"},
  {code: CountryISOEnum.SD, code3: "SDN", name: "Sudan"},
  {code: CountryISOEnum.SR, code3: "SUR", name: "Suriname"},
  {code: CountryISOEnum.SJ, code3: "SJM", name: "Svalbard and Jan Mayen"},
  {code: CountryISOEnum.SZ, code3: "SWZ", name: "Eswatini"},
  {code: CountryISOEnum.SE, code3: "SWE", name: "Sweden"},
  {code: CountryISOEnum.CH, code3: "CHE", name: "Switzerland"},
  {code: CountryISOEnum.SY, code3: "SYR", name: "Syrian Arab Republic"},
  {code: CountryISOEnum.TW, code3: "TWN", name: "Taiwan, Province of China"},
  {code: CountryISOEnum.TJ, code3: "TJK", name: "Tajikistan"},
  {code: CountryISOEnum.TZ, code3: "TZA", name: "Tanzania, United Republic of"},
  {code: CountryISOEnum.TH, code3: "THA", name: "Thailand"},
  {code: CountryISOEnum.TL, code3: "TLS", name: "Timor-Leste"},
  {code: CountryISOEnum.TG, code3: "TGO", name: "Togo"},
  {code: CountryISOEnum.TK, code3: "TKL", name: "Tokelau"},
  {code: CountryISOEnum.TO, code3: "TON", name: "Tonga"},
  {code: CountryISOEnum.TT, code3: "TTO", name: "Trinidad and Tobago"},
  {code: CountryISOEnum.TN, code3: "TUN", name: "Tunisia"},
  {code: CountryISOEnum.TR, code3: "TUR", name: "Turkey"},
  {code: CountryISOEnum.TM, code3: "TKM", name: "Turkmenistan"},
  {code: CountryISOEnum.TC, code3: "TCA", name: "Turks and Caicos Islands"},
  {code: CountryISOEnum.TV, code3: "TUV", name: "Tuvalu"},
  {code: CountryISOEnum.UG, code3: "UGA", name: "Uganda"},
  {code: CountryISOEnum.UA, code3: "UKR", name: "Ukraine"},
  {code: CountryISOEnum.AE, code3: "ARE", name: "United Arab Emirates"},
  {code: CountryISOEnum.GB, code3: "GBR", name: "United Kingdom of Great Britain and Northern Ireland"},
  {code: CountryISOEnum.UM, code3: "UMI", name: "United States Minor Outlying Islands"},
  {code: CountryISOEnum.UY, code3: "URY", name: "Uruguay"},
  {code: CountryISOEnum.UZ, code3: "UZB", name: "Uzbekistan"},
  {code: CountryISOEnum.VU, code3: "VUT", name: "Vanuatu"},
  {code: CountryISOEnum.VE, code3: "VEN", name: "Venezuela (Bolivarian Republic of)"},
  {code: CountryISOEnum.VN, code3: "VNM", name: "Viet Nam"},
  {code: CountryISOEnum.VG, code3: "VGB", name: "Virgin Islands (British)"},
  {code: CountryISOEnum.VI, code3: "VIR", name: "Virgin Islands (U.S.)"},
  {code: CountryISOEnum.WF, code3: "WLF", name: "Wallis and Futuna"},
  {code: CountryISOEnum.EH, code3: "ESH", name: "Western Sahara"},
  {code: CountryISOEnum.YE, code3: "YEM", name: "Yemen"},
  {code: CountryISOEnum.ZM, code3: "ZMB", name: "Zambia"},
  {code: CountryISOEnum.ZW, code3: "ZWE", name: "Zimbabwe"}
];


