export enum USStateEnum {
  'AL' = 'AL',
  'AK' = 'AK',
  'AZ' = 'AZ',
  'AR' = 'AR',
  'AS' = 'AS',
  'CA' = 'CA',
  'CO' = 'CO',
  'CT' = 'CT',
  'DE' = 'DE',
  'DC' = 'DC',
  'FM' = 'FM',
  'FL' = 'FL',
  'GA' = 'GA',
  'GU' = 'GU',
  'HI' = 'HI',
  'ID' = 'ID',
  'IL' = 'IL',
  'IN' = 'IN',
  'IA' = 'IA',
  'KS' = 'KS',
  'KY' = 'KY',
  'LA' = 'LA',
  'ME' = 'ME',
  'MH' = 'MH',
  'MD' = 'MD',
  'MA' = 'MA',
  'MI' = 'MI',
  'MN' = 'MN',
  'MS' = 'MS',
  'MO' = 'MO',
  'MT' = 'MT',
  'NE' = 'NE',
  'NV' = 'NV',
  'NH' = 'NH',
  'NJ' = 'NJ',
  'NM' = 'NM',
  'NY' = 'NY',
  'NC' = 'NC',
  'ND' = 'ND',
  'MP' = 'MP',
  'OH' = 'OH',
  'OK' = 'OK',
  'OR' = 'OR',
  'PW' = 'PW',
  'PA' = 'PA',
  'PR' = 'PR',
  'RI' = 'RI',
  'SC' = 'SC',
  'SD' = 'SD',
  'TN' = 'TN',
  'TX' = 'TX',
  'UT' = 'UT',
  'VT' = 'VT',
  'VA' = 'VA',
  'VI' = 'VI',
  'WA' = 'WA',
  'WV' = 'WV',
  'WI' = 'WI',
  'WY' = 'WY',
  'AE' = 'AE',
  'AA' = 'AA',
  'AP' = 'AP'
}

export const USStateEnumValue = new Map<string, string>([
  [USStateEnum.AL, 'Alabama'],
  [USStateEnum.AK, 'Alaska'],
  [USStateEnum.AZ, 'Arizona'],
  [USStateEnum.AR, 'Arkansas'],
  [USStateEnum.AS, 'American Samoa'],
  [USStateEnum.CA, 'California'],
  [USStateEnum.CO, 'Colorado'],
  [USStateEnum.CT, 'Connecticut'],
  [USStateEnum.DE, 'Delaware'],
  [USStateEnum.DC, 'District of Columbia'],
  [USStateEnum.FM, 'Federated States of Micronesia'],
  [USStateEnum.FL, 'Florida'],
  [USStateEnum.GA, 'Georgia'],
  [USStateEnum.GU, 'Guam'],
  [USStateEnum.HI, 'Hawaii'],
  [USStateEnum.ID, 'Idaho'],
  [USStateEnum.IL, 'Illinois'],
  [USStateEnum.IN, 'Indiana'],
  [USStateEnum.IA, 'Iowa'],
  [USStateEnum.KS, 'Kansas'],
  [USStateEnum.KY, 'Kentucky'],
  [USStateEnum.LA, 'Louisiana'],
  [USStateEnum.ME, 'Maine'],
  [USStateEnum.MH, 'Marshall Islands'],
  [USStateEnum.MD, 'Maryland'],
  [USStateEnum.MA, 'Massachusetts'],
  [USStateEnum.MI, 'Michigan'],
  [USStateEnum.MN, 'Minnesota'],
  [USStateEnum.MS, 'Mississippi'],
  [USStateEnum.MO, 'Missouri'],
  [USStateEnum.MT, 'Montana'],
  [USStateEnum.NE, 'Nebraska'],
  [USStateEnum.NV, 'Nevada'],
  [USStateEnum.NH, 'New Hampshire'],
  [USStateEnum.NJ, 'New Jersey'],
  [USStateEnum.NM, 'New Mexico'],
  [USStateEnum.NY, 'New York'],
  [USStateEnum.NC, 'North Carolina'],
  [USStateEnum.ND, 'North Dakota'],
  [USStateEnum.MP, 'Northern Mariana Islands'],
  [USStateEnum.OH, 'Ohio'],
  [USStateEnum.OK, 'Oklahoma'],
  [USStateEnum.OR, 'Oregon'],
  [USStateEnum.PW, 'Palau'],
  [USStateEnum.PA, 'Pennsylvania'],
  [USStateEnum.PR, 'Puerto Rico'],
  [USStateEnum.RI, 'Rhode Island'],
  [USStateEnum.SC, 'South Carolina'],
  [USStateEnum.SD, 'South Dakota'],
  [USStateEnum.TN, 'Tennessee'],
  [USStateEnum.TX, 'Texas'],
  [USStateEnum.UT, 'Utah'],
  [USStateEnum.VT, 'Vermont'],
  [USStateEnum.VA, 'Virginia'],
  [USStateEnum.VI, 'Virgin Islands'],
  [USStateEnum.WA, 'Washington'],
  [USStateEnum.WV, 'West Virginia'],
  [USStateEnum.WI, 'Wisconsin'],
  [USStateEnum.WY, 'Wyoming'],
  [USStateEnum.AE, 'Armed Forces'],
  [USStateEnum.AA, 'Armed Forces Americas'],
  [USStateEnum.AP, 'Armed Forces Pacific'],
]);
