export const CustomerTransactionLabels = {
  DocType: 'Doc Type',
  DocNumber: 'Doc Number',
  Last4: 'Last 4',
  Last4Placeholder: '****',
  Source: 'Source',
  PaymentMethod: 'Payment Method',
  TransactionTimestamp: 'Payment Date',
  Amount: 'Amount',
  SurchargeAmount: 'Surcharge',
  Total: 'Total',
  SaleVersion: 'Sale Version',
  DateRange: 'Date Range',
  Status: 'Status',
  AuthCode: 'Auth Code',
  UserId: 'User ID',
  UserName: 'User Name',
  Refresh: 'Refresh',
  Export: 'Export',
} as const;
