export const BrandingLabels = {
  Name: "Name",
  CompanyPortalUrl: "Company Portal URL",
  CustomerPortalUrl: "Customer Portal URL",
  PaymentFormsUrl: "Payment Forms URL",
  SaleFrom: "Sale From",
  ReceiptFrom: "Receipt From",
  EmailFrom: "Email From",
  ProductName: "Product Name",
  SignatureFormatted: "Signature Formatted",
  SupportPhone: "Support Phone",
  SupportEmail: "Support Email",
  ApiKeyKeyVaultSecretName: "Azure ApiKey KeyVault Secret Name",
  WebhookVerificationKeyKeyVaultSecretName: "Azure Webhook VerificationKey KeyVault Secret Name",
  Select: 'Select...',
  Submit: 'Save',
  Close: 'Close',
  Cancel: 'Cancel',
  CreateBranding: 'Create Branding',
  EditBranding: 'Edit Branding',
  DisableHeader: 'Disable Branding',
  Disable: 'Disable',
  Enable: 'Enable',
  Default: 'Default Branding',
  MakeDefault: 'Make Default',
} as const;
