export const CompanyPaymentFormsLabels = {
  ID: 'ID',
  Name: 'Name',
  PaymentFormCode: 'Payment Form Code',
  CreateNew: 'Create New',
  Refresh: 'Refresh',
  ShowInactive: 'Show Inactive',
  NewPaymentForm: 'New Payment Form',
  EditPaymentForm: 'Edit Payment Form',
  PaymentFormUrl: 'Payment Form URL',
  PaymentFormUrlCopied: 'Payment Form URL copied',
  PaymentFormsCompanyIdRequired: 'Company Id for Payment Forms is not configured',
  PaymentFormsUrlRequired: 'Payment Forms URL is not configured',
  PaymentFormTemplate: 'Payment Form Template',
  Save: 'Save',
  Cancel: 'Cancel',
  InvalidCode: 'Only letters, numbers, and hyphens are allowed. Spaces are not allowed.',
  Activate: 'activate',
  Deactivate: 'deactivate',
  ActivateHint: 'Activate',
  DeactivateHint: 'Deactivate',
  ActivateDeactivateHeader: (action: string) => `${action.charAt(0).toUpperCase()}${action.slice(1)} Payment Form`,
  ActivateDeactivateMessage: (action: string) => `Are you sure you want to ${action} the form?`,
  ActivateDeactivateConfirm: (action: string) => `Yes, ${action}`,
  ActivateDeactivateCancel: 'No'
} as const;
