import {capitalizeFirstLetter} from "../../../../../../common/src/lib/helpers/string.helper";

export const UserLabels = {
    UserEditHeader: 'User Information',
    FirstName: 'First Name',
    MiddleName: 'Middle Name',
    LastName: 'Last Name',
    Email: 'Email',
    ResetPassword: 'Reset Password',
    MustChangePassword: 'Must Change Password on Next Logon',
    MainPhone: 'Main Phone',
    WorkPhone: 'Work Phone',
    Mobile: 'Mobile',
    Fax: 'Fax',
    CCEmail: 'CC Email',
    ContactInfo: 'Contact Info',
    Submit: 'Save',
    Cancel: 'Cancel',
    RolesErrorMessage: 'Roles are required',
    EMVKey: 'EMV Key',
    AccountDisabled: 'Account disabled',
    Pending: 'Pending',
    CreateNew: 'Create New',
    ReInvite: 'Resend Invitation',
    InvitationSend: 'Invitation sent',
    Disable: 'disable',
    Enable: 'enable',
    EnabledDisabled: (enable: boolean) => `User ${enable ? 'enabled': 'disabled'}`,
    EnableDisableHint: (enable: boolean) => `${enable ? 'Enable': 'Disable'}`,
    EnableDisableHeader: (action: string) => `${capitalizeFirstLetter(action)} User`,
    EnableDisableMessage: (action: string, email: string) => `Are you sure you want to ${action} the user ${email}?`,
    EnableDisableConfirm: (action: string) => `Yes, ${action}`,
    EnableDisableCancel: 'No',
    MaxNumberOfUsers: (count: number) => `Max number of users ${count} exceeded. Please contact system administrator to increase the limit.`,
    IdHeader: 'ID',
    EmailHeader: 'Email',
    RolesHeader: 'Roles',
    ActionsHeader: '',
    Change: 'Change',
    CheckAllMessage: 'Check All',
    UnCheckAllMessage: 'Uncheck All',
    RolesInEntity: (entityName: string) => `Roles in ${entityName}`,
    Entity: 'Entity',
    Roles: 'Roles',
    Refresh: 'Refresh',
} as const;
