export const CustomerCompanyInvitationLabels = {
  Password: 'Password',
  ConfirmPassword: 'Confirm New Password',
  FirstName: "First Name",
  MiddleName: "Middle Name",
  LastName: "Last Name",
  Submit: 'Join',
  Accept: 'Accept Invitation',
  ErrorMessage: 'Oops! Something went wrong',
  InvitationConfirmedMessage: `Thank you for joining!`,
  GoToPortalMessage: 'Now you can log in to the portal',
  InvitationMessage: `We invite you to join`,
  AcceptInvitationMessage: (customerName: string) => `You are invited to join ${customerName}.`,
  AcceptInvitationHint: 'Your account is already registered, so you keep using your current password.',
  InvitationAcceptedMessage: 'Invitation accepted!',
  AlreadyRegisteredMessage: (customerName: string) => `You are already registered in ${customerName}.`,
  AlreadyRegisteredHint: 'Welcome to the portal! Log in with your current password.',
  Required: '(Required)',
  Greetings: (name: string) => `Hello, ${name}!`,
  SuccessMessage: (companyName: string) => `Thank you! Please check your email to confirm invitation`,
  PasswordHint: (minLength, maxLength) => `The password must be ${minLength}-${maxLength} characters long, contain upper and lower case and special characters`,
  GoToPortal: 'Go to Portal',
} as const;
