export const CompanyLabels = {
  Ok: "Yes",
  Cancel: "Cancel",
  Create: "Create New",
  HideTrusted: "Hide Trusted Platforms",
  HideInactive: "Hide Inactive",
  CompanyDisabled: "[Company Disabled]",
  Id: "ID",
  ExternalId: "External ID",
  PlatformId: "Platform ID",
  PlatformName: "Platform Name",
  LegalName: "Legal Name",
  Administrators: "Administrators",
  ActiveUsers: "Active Users",
  ActiveTokens: "Active Tokens",
  Enable: "Enable",
  EnableCompanyHeader: "Enable Company",
  EnableCompanyBody: (companyName) => `Are you sure you want to enable ${companyName} company?`,
  EnableCompanyFinished: "Company enabled",
  Disable: "Disable",
  DisableCompanyHeader: "Disable Company",
  DisableCompanyBody: (companyName) => `Are you sure you want to disable ${companyName} company?`,
  DisableCompanyFinished: "Company disabled",
  SubscriptionCheckHeader: "Subscription check",
  SubscriptionIsActiveResponse: "Subscription is active",
  SubscriptionIsNotActiveResponse: "Subscription is not active",
  CreateHeader: "Create New Company",
  EditHeader: "Edit Company",
  SelectPlatformPlaceholder: "Select Platform",
  AdministratorPlaceholder: (isEditMode: boolean) => `${isEditMode ? "Add Administrator" : "Administrator"}`,
  Administrator: "Administrator",
  DisplayName: "Display Name",
  Logo: "Logo",
  EnableGlobalPayments: "Enable Global Payments",
  CustomerRegistrationOnCheckout: "Enable Customer Registration Option on Checkout Page",
  Street: "Street",
  City: "City",
  State: "State",
  Zip: "Zip",
  Country: "Country",
  Phone: "Phone",
  Email: "Email",
  Website: "Website",
  WebsiteHint: "https://",
  EmailOptions: "Email Options",
  MailingMethod: "Mailing Method",
  FromAddress: "From Address",
  SMTPServer: "SMTP Server",
  SecurityMode: "Security Mode",
  Port: "Port",
  User: "User",
  Password: "Password",
  VaultCompanyID: "Vault Company ID",
  CompanyIdForPaymentForms: "Company Id for Payment Forms",
  VaultUserID: "Vault User ID",
  VaultAuthorizationKey: "Vault Authorization Key",
  TokenLimit: "Token Limit",
  TokenLimitHint: "Set max number of tokens or leave it blank for no limit",
  OAuth10WebhookUrl: "Webhook URL",
  OAuth10SignatureMethod: "Signature Method",
  OAuth10ConsumerKey: "Consumer Key",
  OAuth10ConsumerSecret: "Consumer Secret",
  OAuth10AccessToken: "Access Token",
  OAuth10TokenSecret: "Token Secret",
  OAuth10Realm: "Realm",
  HmacSha256WebhookUrl: "Webhook URL",
  HmacSha256Secret: "Secret",
  Save: "Save",
  Test: "Test",
  Connect: "Connect",
  Refresh: "Refresh",
  Select: "Select...",
  EmailSale: 'Email Sales (Invoices, Sales Orders, Deposit)',
  EmailReceipt: 'Email Receipt Upon Payment',
  SalesEmailOptionHint: "Platform-level Settings",
  MaxUsersInCompany: "Max Number of Company Users",
  MaxCustomerUsersInCustomer: "Max Number of Users per Customer",
  SuppressWebhookHeader: "Suppress the Following Webhook Events:",
  SuppressWebhookHint: "Suppressing webhook events can lead to data inconsistency on the merchant side. \n" +
    "Make sure this is what you really need.",
  SaleWebhookEvents: 'Sale Events',
  PaymentMethodWebhookEvents: 'Payment Method Events',
  CustomerWebhookEvents: 'Customer Events',
  PaymentWebhookEvents: 'Payment Events',
  ConnectToVaultHeader: 'Connect to Vault',
  ConnectToVaultBody: 'Subscription is active',
  VaultFeatureNameHeader: 'Vault Features Enabled',
  EmailPaymentFeature: 'Email Payments',
  CustomerPortalFeature: 'Customer Portal',
  SurchargesFeature: 'Surcharges',
  PaymentFormsFeature: 'Payment Forms',
  VaultAvailablePaymentMethods: 'Vault Payment Methods Available',
  MissingPaymentMethod: '! disabled in Company Payment Settings',
  NoFeatures: 'No available Vault Features',
  LastUpdated: 'last updated on',
} as const;
