export const PlatformLabels = {
  CreatePlatform: 'Create Platform',
  EditPlatform: 'Edit Platform',
  PlatformName: 'Platform Name',
  TrustedPlatform: 'Trusted Platform',
  UseEpsCheckout: 'Use EPS Checkout Page',
  SendgridSettings: 'Sendgrid Settings',
  Branding: 'Branding',
  CompanyPortalUrl: 'Company Portal URL',
  CustomerPortalUrl: 'Customer Portal URL',
  PaymentFormsUrl: 'Payment Forms URL',
  ProductName: 'Product Name',
  SaleFrom: 'Sale From',
  ReceiptFrom: 'Receipt From',
  EmailFrom: 'Email From',
  SignatureFormatted: 'Signature Formatted',
  SupportPhone: 'Support Phone',
  SupportEmail: 'Support Email',
  EmailSales: 'Email Sales (Invoices, Sales Orders, Deposit)',
  EmailReceipt: 'Email Receipt Upon Payment',
  VaultProductId: 'Vault Product Id',
  VaultPaymentRequestsTypeOnCheckoutPage: 'Vault Payment Requests Type On Checkout Page',
  EmailPaymentsFeature: 'Email Payments',
  PaymentFormsFeature: 'Payment Forms',
  CustomerPortalFeature: 'Customer Portal',
  SurchargesFeature: 'Surcharges',
  VaultFeatureName: 'Vault Feature Name',
  CustomFieldsEnable: 'Enable Custom Fields',
  AdvancedFieldsEnable: 'Enable Advanced Fields',
  RefreshToken: 'Refresh Token',
  RefreshTokenCopied: 'Refresh Token copied',
  GenerateApiToken: 'Generate Api Token',
  WebhookAuthType: 'Webhook Auth Type',
  SaleWebhookEnabledEvents: 'Sale Events',
  PaymentMethodWebhookEnabledEvents: 'Payment Method Events',
  CustomerRegistrationOnCheckout: "Enable Customer Registration Option on Checkout Page",
  CustomerWebhookEnabledEvents: 'Customer Events',
  PaymentWebhookEnabledEvents: 'Payment Events',
  WebhookBypassDnsCache: 'Bypass DNS Cache',
  OAuth10WebhookUrl: 'Webhook URL',
  OAuth10SignatureMethod: 'Signature Method',
  OAuth10ConsumerKey: 'Consumer Key',
  OAuth10ConsumerSecret: 'Consumer Secret',
  OAuth10AccessToken: 'Access Token',
  OAuth10TokenSecret: 'Token Secret',
  OAuth10Realm: 'Realm',
  HmacSha256WebhookUrl: 'Webhook URL',
  HmacSha256Secret: 'Secret',
  TestWebhook: 'Test',
  WebhookAttemptsNumber: 'Number of Attempts',
  WebhookAttemptsNumberValues: [`1 attempt, no retry`,
    `2 - retry in 5m`,
    `3 - retry in 5m, 15m`,
    `4 - retry in 5m, 15m, 30m`,
    `5 - retry in 5m, 15m, 30m, 45m`,
    `6 - retry in 5m, 15m, 30m, 45m, 1.5h`,
    `7 - retry in 5m, 15m, 30m, 45m, 1.5h, 3h`,
    `8 - retry in 5m, 15m, 30m, 45m, 1.5h, 3h, 6h`,
    `9 - retry in 5m, 15m, 30m, 45m, 1.5h, 3h, 6h, 12h`,
    `10 - retry in 5m, 15m, 30m, 45m, 1.5h, 3h, 6h, 12h, 24h`
  ],
  Select: 'Select...',
  Submit: 'Save',
  Close: 'Close',
  Cancel: 'Cancel',
  Ok: 'Yes',
  CreateNew: 'Create New',
  Refresh: 'Refresh',
  HideInactive: 'Hide Inactive',
  Enable: 'Enable',
  Disable: 'Disable',
  Delete: 'Delete',
  EnablePlatformHeader: 'Enable Platform',
  EnablePlatformBody: (platformName: string) => `Are you sure you want to enable the Platform ${platformName}?`,
  EnablePlatformFinished: 'Platform enabled',
  DisablePlatformHeader: 'Disable Platform',
  DisablePlatformBody: (platformName: string) => `Are you sure you want to disable the Platform ${platformName}?`,
  DisablePlatformFinished: 'Platform disabled',
  DeletePlatformHeader: 'Delete Platform',
  DeletePlatformBody: (platformName: string) => `Are you sure you want to delete the Platform ${platformName}?`,
  DeletePlatformFinished: 'Platform deleted',
} as const;
