export const CreditCardInfoGroupLabels = {
  CardNumber: "Card number",
  Holder: "Name on Card",
  ExpiryDate: "Expiry Date",
  Expired: "Expired",
  CVV: "CVV",
  Company: "Company",
  FirstName: "First Name",
  MiddleName: "Middle Name",
  LastName: "Last Name",
  Address: "Address",
  Address1: "Street address or P.O. Box",
  Address2: "Apt, suite, unit, building, floor, etc.",
  City: "City",
  State: "State/Province",
  Zip: "Zip/Postal Code",
  Country: "Country",
  Phone: "Phone",
  Email: "Email",
  Select: "Select...",
  PaymentDefault: "Payment Default",
  BatchDefault: "Batch Default",
  CustomerDefault: "Customer Default",
  IsPrivate: "Hide This Payment Method From Other Users",
  SavePaymentMethod: "Save Payment Method",
} as const;
