export const TransactionLabels = {
  ID: 'ID',
  DocType: 'Doc Type',
  DocNumber: 'Doc Number',
  Last4: 'Last 4',
  Last4Placeholder: '****',
  Source: 'Source',
  PaymentMethod: 'Payment Method',
  TransactionTimestamp: 'Payment Date',
  Amount: 'Amount',
  Surcharge: 'Surcharge',
  Total: 'Total',
  SaleVersion: 'Sale Version',
  DateRange: 'Date Range',
  Status: 'Status',
  AuthCode: 'Auth Code',
  ProductId: 'Product ID',
  Refresh: 'Refresh',
  Export: 'Export',
} as const;
