import {
  SaleEmailTemplateData
} from "../../../../models/sale/template/sale-email-template-data.model";
import {InvoiceItemDetailTypeEnum} from "../../../../enums/sale/invoice-item-detail-type.enum";

export class InvoiceItemsDataService {
  static get templateData(): SaleEmailTemplateData {
    return {
      companyInfo: null,
      logo: null,
      fullTemplate: null,
      saleShortInfo: null,
      saleFullInfo: null,
      saleAdditionalInfo: null,
      billingAddress: null,
      shippingAddress: null,
      shippingInfo: null,
      customFieldsInfo: null,
      invoiceItems: [
        {
          detailType: InvoiceItemDetailTypeEnum.SALES_ITEM_LINE_DETAIL,
          name: 'Installation',
          sku: '001',
          description: 'Installation of landscape design',
          quantity: '1',
          amount: '50.00',
          rate: '50.00',
          tax: '0',
          taxable: false,
          serviceDate: '2024-12-10',
          categoryClass: 'class1',
          other1: 'other1',
          other2: 'other2',
        },
        {
          detailType: InvoiceItemDetailTypeEnum.SUBTOTAL_LINE,
          name: null,
          sku: null,
          description: 'Subtotal: $50.00',
          quantity: null,
          amount: null,
          rate: null,
          tax: null,
          taxable: false,
          serviceDate: null,
          categoryClass: null,
          other1: null,
          other2: null,
        },
        {
          detailType: InvoiceItemDetailTypeEnum.GROUP_LINE_DETAIL,
          name: 'Bundle',
          sku: null,
          description: 'Water feature kit',
          quantity: '1',
          amount: '65.00',
          rate: '65.00',
          tax: '0',
          taxable: false,
          serviceDate: null,
          categoryClass: null,
          other1: 'other1',
          other2: 'other2',
        },
        {
          detailType: InvoiceItemDetailTypeEnum.SALES_ITEM_LINE_DETAIL,
          isChild: true,
          name: 'Pump',
          sku: null,
          description: 'Fountain Pump',
          quantity: '3',
          amount: '45.00',
          rate: '15.00',
          tax: '0.1',
          taxable: true,
          serviceDate: null,
          categoryClass: null,
          other1: 'other1',
          other2: 'other2',
        },
        {
          detailType: InvoiceItemDetailTypeEnum.SALES_ITEM_LINE_DETAIL,
          isChild: true,
          name: 'Soil',
          sku: null,
          description: '2 cubic ft. bag',
          quantity: '2',
          amount: '20.00',
          rate: '10.00',
          tax: '0.1',
          taxable: true,
          serviceDate: null,
          categoryClass: null,
          other1: 'other1',
          other2: 'other2',
        }],
      customerMemo: null,
      customerName: null,
      subTotal: 12,
      taxPercentage: 0.1,
      taxAmount: 0.5,
      discount: 2,
      discountExpDate: null,
      discountExpDateFormatted: null,
      isDiscountExpired: false,
      shippingCost: 2,
      tip: 0.5,
      appliedAmount: 2,
      amountDue: 71.55,
      total: 121.55,
      currency: 'USD',
      customFieldsEnabled: null,
      advancedFieldsEnabled: null
    }

  }

}
