export const AchGroupLabels = {
  NameOnAccount: "Name on Account",
  Routing: "Routing #",
  CanadaRoutingPlaceholder: "0-###-#####",
  CanadaRoutingHint: "Enter your Bank Number (3 digits) followed by your Branch Transit Number (5 digits)",
  USRoutingHint: "Enter 9 digits starting with 0, 1, 2 or 3",
  Account: "Account #",
  AccountType: "Account Type",
  Company: "Company",
  FirstName: "First Name",
  MiddleName: "Middle Name",
  LastName: "Last Name",
  Address: "Address",
  Address1: "Street address or P.O. Box",
  Address2: "Apt, suite, unit, building, floor, etc.",
  City: "City",
  State: "State/Province",
  Zip: "Zip/Postal Code",
  Country: "Country",
  Phone: "Phone",
  Email: "Email",
  Select: "Select...",
  PaymentDefault: "Payment Default",
  BatchDefault: "Batch Default",
  CustomerDefault: "Customer Default",
  IsPrivate: "Hide This Payment Method From Other Users",
  SavePaymentMethod: "Save Payment Method",
} as const;
