import {DocTypeEnum, DocTypeEnumValue} from "@eps/common";
import {ObjectHelper} from "../../../../../common/src/lib/helpers/object.helper";

export const SaleLabels = {
  Close: "Close",
  Print: 'Print',
  View: (docType: DocTypeEnum) => `View ${DocTypeEnumValue.get(docType)}`,
  PayNow: 'Pay Now',
  PaymentAmount: 'Payment Amount',
  CopyFromBillToAddress: 'Copy from Bill To Address',
  PaymentSuccess: (currency: string, paymentAmount: string, surchargeAmount: string, totalIncludingSurcharge: string) => `Your Payment of ${currency}${paymentAmount}${ObjectHelper.isDefined(surchargeAmount) ? "(Surcharge: " + currency + surchargeAmount + ". Total: " + currency + totalIncludingSurcharge +")": ""} Successfully Completed`,
  AuthorizationID: 'Authorization ID:',
  ApprovalID: 'Approval ID:',
  CCPaymentAmountLimitMessage: (currency: string, amount: string, docType: string) => `Credit Card Payments have been limited to ${currency}${amount} for this ${docType}`,
  CCMultiplePaymentAmountLimitMessage: (currency: string, amount: string) => `Credit Card Payments have been limited to ${currency}${amount}`,
  CCMultipleTotalLimitMessage: (currency: string, amount: string) => `Total must be less than or equal to ${currency}${amount}`,
  CCMultipleTotalMinMessage: (currency: string, amount: string) => `Total must be greater than ${currency}${amount}`,
  ContactCompany: (companyName: string) => `Please contact ${companyName}`,
  DiscountExpired: 'Discount expired',
  Submit: "Complete Order",
  Date: "Date",
  DateRange: "Date Range",
  AmountDue: "Amount Due",
  AmountPaid: "Amount Paid",
  TotalAmountToCharge: "Total Amount To Charge",
  Total: "Total Including Surcharge",
  TotalAmountDue: "Total Amount Due",
  AppliedAmount: "Applied Amount",
  PaymentStatus: "Payment Status",
  Refresh: "Refresh",
  ProcessPayment: 'Process Payment',
  ShowArchived: 'Show Archived',
  ShowPaid: 'Show Paid',
  Cancel: "Cancel",
  Invoice: "Invoice",
  AmountToCharge: "Amount To Charge",
  BackToInvoiceList: "Back to Invoices",
  MultiplePaymentInvoiceNumberStringExceedsLimit: "The limit of selected invoices has been exceeded",
  SaleHasChangedErrorMessage: 'Sale has changed',
  SaleAmountDueHasChanged: 'Sale amount due has changed',
  ACHPaymentsDisabled: 'ACH payments have been disabled, please reload a page to view available payment options',
  CCPaymentsDisabled: 'Credit Card payments have been disabled, please reload a page to view available payment options',
  PartialPaymentsDisabledErrorMessage: 'Partial payments have been disabled, please reload a page to view available payment options',
  Surcharge: (surchargePercent: number) => `Surcharge ${surchargePercent}%`,
} as const;
